baseurl = "https://www.fconnect.ml/"
languageCode = "en"
title = "FConnect+"
theme = "vex-hugo"

[params]
  description = ""

  # Put your custom stylesheets and scripts
  custom_stylesheets = []
  custom_scripts = []

  # Additional meta
  [[params.meta]]
    name = ""
    description = ""

  # Navigation bar informations
  [params.navbar]
    logo = "FConnect+"
    [[params.navbar.menu]]
      link = "#"
      text = "Open Resources (soon)"
    #[[params.navbar.menu]]
      #link = "#feature"
      #text = "ABOUT"
    #[[params.navbar.menu]]
      #link = "#gallery"
      #text = "SERVICES"
    #[[params.navbar.menu]]
      #link = "#testimonials"
      #text = "CONTACT"

  # Header
  [params.header]
    title = "Reliable resources and information for foster youth"
    text = ""
    [params.header.image]
      path = "images/fconnectlogo3.png"
      alt = "Watch"
    [params.header.button]
      link = "#about"
      text = "Soon on Appstore"

  # Features
  #[params.features]
    #title = "Our Core Features"
    #[params.features.image]
      #path = "images/watch-2.png"
      #alt = "Watch"
    # Menu at the left of the image
    #[[params.features.left]]
      #icon = "tf-ion-ios-alarm-outline"
      #title = "Social Media Account"
      #text = "User can create an account and login via the iPhone"
    #[[params.features.left]]
      #icon = "tf-ion-ios-bell-outline"
      #title = "Share Food Photos"
      #text = "User can take a photo of their favourite foods and post it with details and location"
    #[[params.features.left]]
      #icon = "tf-ion-ios-cart-outline"
      #title = "Wall of Foods"
      #text = "User can view a news feed of food photos shared by their friends"
    # Menu at the right of the image
    #[[params.features.right]]
      #icon = "tf-ion-ios-alarm-outline"
      #title = "Comments"
      #text = "User can comments on the post"
    #[[params.features.right]]
      #icon = "tf-ion-ios-bell-outline"
      #title = "View Details and Location"
      #text = "User can view the details of the post and the location of the photo was taken"
    #[[params.features.right]]
      #icon = "tf-ion-ios-cart-outline"
      #title = "User Profile"
      #text = "User can view all the photos of foods that they have uploaded on their profile"

  [params.promo]
    title = "Personalized resources to help you with few clicks away in the palm of your hand"
    text = ""
    [params.promo.image]
      path = "images/holdphone.png"
      alt = "Fconnect+ apps"

  [params.feature_list]
    title = "Problem and Solution"
    [[params.feature_list.items]]
      image = "images/problemimage.jpg"
      title = "Problem"
      text = "About 25,000 foster youth age out of Foster system every year.  25% are homeless,  37% are high school drop outs, only 3% graduate out of college, more than half are unemployed,  90% live in poverty earning less than $10,000 per year. There are so many resources available to foster youth from Federal Government, State Government, City Council, and Non-Profit Organization scattered all over the internet and unknown to most foster youth."
      button_link = "https://www.nfyi.org/51-useful-aging-out-of-foster-care-statistics-social-race-media/"
      button_text = "Reference"
    [[params.feature_list.items]]
      image = "images/30StandingCombine.png"
      title = "Solution"
      text = "With FConnect+ mobile app, all these urgent and important information stays in the user's pocket and goes to the user through push notification when the user need it instead of the user searching on the internet. Each information ranked based on the most relevant personalized to each user from regular questionaire from time to time."
      button_link = ""
      button_text = "Download (Soon)"

  [params.gallery]
    title = "Take a peek inside the apps"
    # Set the image directory to use as base
    directory = "images/showcase"
    # Set the images to show in the gallery
    images = ["fconnect1.png", "fconnect2.png", "fconnect3.png", "fconnect4.png", "fconnect5.png", "fconnect6.png", "fconnect7.png", "fconnect8.png", "fconnect9.png"]

  [params.call_to_action]
    title = "🏆 Second Place Winner Paypal Opportunity Hack 2019 🏆"
    #text = "We will update you when we release the apps and the milestones achieved via email"
    placeholder = "Your Email Address Here"
    button_text = "DEVPOST PAGE"
    link = "https://devpost.com/software/fconnect"

  [params.testimonials]
    title = "Our Team"
    [[params.testimonials.blocks]]
      text = ""
      name = "Gregory Mayo"
      position = ""
      image = "images/profilepic/greg.png"
    [[params.testimonials.blocks]]
      text = ""
      name = "Kimleng Hor"
      position = ""
      image = "images/profilepic/kim.png"
    [[params.testimonials.blocks]]
      text = ""
      name = "Samina Qazi"
      position = ""
      image = "images/profilepic/samina.png"
    [[params.testimonials.blocks]]
      text = ""
      name = "Shafie Mukhre"
      position = ""
      image = "images/profilepic/shafie.png"
    [[params.testimonials.blocks]]
      text = ""
      name = "Basmah Altimimi"
      position = ""
      image = "images/profilepic/basmah.jpeg"
    #[params.testimonials.button]
      #link = ""
      #text = "Join Us!"

  # Footer uses navbar data
