baseurl = "http://www.callbacks.ml/"
languageCode = "en"
title = "callback"
theme = "vex-hugo"

[params]
  description = ""

  # Put your custom stylesheets and scripts
  custom_stylesheets = []
  custom_scripts = []

  # Additional meta
  [[params.meta]]
    name = ""
    description = ""

  # Navigation bar informations
  [params.navbar]
    logo = "{callback}"
    #[[params.navbar.menu]]
      #link = "#promo"
      #text = "Our mission"
    #[[params.navbar.menu]]
      #link = "#feature"
      #text = "ABOUT"
    #[[params.navbar.menu]]
      #link = "#gallery"
      #text = "SERVICES"
    #[[params.navbar.menu]]
      #link = "#testimonials"
      #text = "CONTACT"

  # Header
  [params.header]
    title = "Recall computer science basics"
    text = "{callback}"
    [params.header.image]
      path = "images/callbacklogo.jpg"
      alt = "Watch"
    [params.header.button]
      link = "#promo"
      text = "Our Mission"

  # Features
  #[params.features]
    #title = "Our features"
    #[params.features.image]
      #path = "images/watch-2.png"
      #alt = "Watch"
    # Menu at the left of the image
    #[[params.features.left]]
      #icon = "tf-ion-ios-alarm-outline"
      #title = "Social Media Account"
      #text = "User can create an account and login via the iPhone"
    #[[params.features.left]]
      #icon = "tf-ion-ios-bell-outline"
      #title = "Share Food Photos"
      #text = "User can take a photo of their favourite foods and post it with details and location"
    #[[params.features.left]]
      #icon = "tf-ion-ios-cart-outline"
      #title = "Wall of Foods"
      #text = "User can view a news feed of food photos shared by their friends"
    # Menu at the right of the image
    #[[params.features.right]]
      #icon = "tf-ion-ios-alarm-outline"
      #title = "Comments"
      #text = "User can comments on the post"
    #[[params.features.right]]
      #icon = "tf-ion-ios-bell-outline"
      #title = "View Details and Location"
      #text = "User can view the details of the post and the location of the photo was taken"
    #[[params.features.right]]
      #icon = "tf-ion-ios-cart-outline"
      #title = "User Profile"
      #text = "User can view all the photos of foods that they have uploaded on their profile"

  #[params.technology]
    #title = "How we build this"
    #[params.technology.image]
      #path = "images/quizyourself.png"

[params.technologygallery]
    title = "How we build this"
    # Set the image directory to use as base
    directory = "images/technology"
    # Set the images to show in the gallery
    images = ["askquestion80.png", "addanswer80.png", "quizyourself80.png"]

  [params.promo]
    title = "Our mission is to help students get a great job by going back to basic"
    text = ""
    [params.promo.image]
      path = "images/holdphone.png"
      alt = "Fconnect+ apps"

  [params.feature_list]
    title = "Problem and Solution"
    [[params.feature_list.items]]
      #image = "images/rejection.jpeg"
      title = "Problem"
      text = "Students understand, however are not able  --and need practice -- to explain CS fundamentals properly. Students need practice in Students desperately needs referrals. It’s difficult for employee in big companies to judge whether the students has a strong fundamentals or not if he/she would like to refer the students."
      button_link = "https://www.nfyi.org/51-useful-aging-out-of-foster-care-statistics-social-race-media/"
      button_text = "Reference"
    [[params.feature_list.items]]
      #image = "images/stacks.png" 
      title = "Solution"
      text = "{callback} app trains university students with CS fundamentals by answering questions verbally. Premium subscription gave qualified students the personalized access to recruiters and referrals. "
      button_link = ""
      button_text = "Download (Soon)"

  [params.gallery]
    title = "Take a peek inside the apps"
    # Set the image directory to use as base
    directory = "images/showcase"
    # Set the images to show in the gallery
    images = ["callback1.png", "callback2.png", "callback3.png", "callback4.png", "callback5.png", "callback6.png", "callback8.png"]

  [params.call_to_action]
    #title = "🏆 Second Place Winner Paypal Opportunity Hack 2019 🏆"
    #text = "We will update you when we release the apps and the milestones achieved via email"
    #placeholder = "Your Email Address Here"
    button_text = "DEVPOST PAGE"
    link = "https://devpost.com/software/callback"

  [params.testimonials]
    title = "Our Team"
    [[params.testimonials.blocks]]
      text = ""
      name = "Kimleng Hor"
      position = ""
      image = "images/profilepic/kim.png"
    [[params.testimonials.blocks]]
      text = ""
      name = "Shafie Mukhre"
      position = ""
      image = "images/profilepic/shafie.png"
    [[params.testimonials.blocks]]
      text = ""
      name = "Eunice Oh"
      position = ""
      image = "images/profilepic/eunice.jpeg"
    [[params.testimonials.blocks]]
      text = ""
      name = "Cheng Chin Lim"
      position = ""
      image = "images/profilepic/cheng.jpeg"
    [[params.testimonials.blocks]]
      text = ""
      name = "Abraham Tesfay"
      position = ""
      image = "images/profilepic/abraham.jpg"
    [[params.testimonials.blocks]]
      text = ""
      name = "Kimlong Hor"
      position = ""
      image = "images/profilepic/kimlong.JPG"
    #[params.testimonials.button]
      #link = ""
      #text = "Join Us!"

  # Footer uses navbar data
