baseurl = "https://www.eatstagram.ml/"
languageCode = "en"
title = "FConnect+"
theme = "vex-hugo"

[params]
  description = ""

  # Put your custom stylesheets and scripts
  custom_stylesheets = []
  custom_scripts = []

  # Additional meta
  [[params.meta]]
    name = ""
    description = ""

  # Navigation bar informations
  [params.navbar]
    logo = "FConnect+"
    [[params.navbar.menu]]
      link = "#"
      text = "Contribute to Open Resources"
    #[[params.navbar.menu]]
      #link = "#feature"
      #text = "ABOUT"
    #[[params.navbar.menu]]
      #link = "#gallery"
      #text = "SERVICES"
    #[[params.navbar.menu]]
      #link = "#testimonials"
      #text = "CONTACT"

  # Header
  [params.header]
    title = "Find the foods you love. And the foods your friends love."
    text = ""
    [params.header.image]
      path = "images/applogoforwebsite.png"
      alt = "Watch"
    [params.header.button]
      link = "#about"
      text = "Beta Ready. Soon on Appstore"

  # Features
  #[params.features]
    #title = "Our Core Features"
    #[params.features.image]
      #path = "images/watch-2.png"
      #alt = "Watch"
    # Menu at the left of the image
    #[[params.features.left]]
      #icon = "tf-ion-ios-alarm-outline"
      #title = "Social Media Account"
      #text = "User can create an account and login via the iPhone"
    #[[params.features.left]]
      #icon = "tf-ion-ios-bell-outline"
      #title = "Share Food Photos"
      #text = "User can take a photo of their favourite foods and post it with details and location"
    #[[params.features.left]]
      #icon = "tf-ion-ios-cart-outline"
      #title = "Wall of Foods"
      #text = "User can view a news feed of food photos shared by their friends"
    # Menu at the right of the image
    #[[params.features.right]]
      #icon = "tf-ion-ios-alarm-outline"
      #title = "Comments"
      #text = "User can comments on the post"
    #[[params.features.right]]
      #icon = "tf-ion-ios-bell-outline"
      #title = "View Details and Location"
      #text = "User can view the details of the post and the location of the photo was taken"
    #[[params.features.right]]
      #icon = "tf-ion-ios-cart-outline"
      #title = "User Profile"
      #text = "User can view all the photos of foods that they have uploaded on their profile"

  #[params.promo]
    #title = "Designed by iOS professionals, with love ❤ for amazing foods arounds us"
    #text = ""
    #[params.promo.image]
      #path = "images/eatstagram.png"
      #alt = "Watch"

  #[params.feature_list]
    #title = "Why Use Eatstagram"
    #[[params.feature_list.items]]
      #image = "images/front.png"
      #title = "Upload all the food photos"
      #text = "All of us are taking the photo of the foods before we eat only to save it inside our phone without even looking at it ever again. Sometimes we planned to upload it on social media, yet we forget or never uploaded it because it does not look 'perfect enough' to impress our public social media followers. With Eastagram, you will upload all your food photos to share with your small group of families and close friends."
      #button_link = ""
      #button_text = "Check Features"
    #[[params.feature_list.items]]
      #image = "images/front.png"
      #title = "Buy mealplans with weekly subscription"
      #text = "With Eastagram, you can subscribes to your favourite meals from nearby restaurants delivered on schedule to you home or office at breakfast/lunch/dinner time without on-demand delivery fees. In the near future, Eatstagram will also provides our very own 'original' series of meals that taste better and healtier at affordable price range."
      #button_link = ""
      #button_text = "Check Features"

  [params.gallery]
    title = "Take a peek inside the apps"
    # Set the image directory to use as base
    directory = "images/showcase"
    # Set the images to show in the gallery
    images = ["showcase-1.png", "showcase-2.png", "showcase-3.png", "showcase-4.png", "showcase-5.png", "showcase-6.png", "showcase-7.png", "showcase-8.png"]

  [params.call_to_action]
    title = "Get Product Updates"
    text = "We will update you when we release the apps and the milestones achieved via email"
    placeholder = "Your Email Address Here"
    button_text = "Subscribe"

  [params.testimonials]
    title = "Our Team"
    [[params.testimonials.blocks]]
      text = ""
      name = "Gregory Mayo"
      position = "iOS Developer"
      image = "images/profilepic/greg.png"
    [[params.testimonials.blocks]]
      text = ""
      name = "Kimleng Hor"
      position = "Lead iOS Developer"
      image = "images/profilepic/kim.png"
    [[params.testimonials.blocks]]
      text = ""
      name = "Samina Qazi"
      position = "iOS Developer"
      image = "images/profilepic/samina.png"
    [[params.testimonials.blocks]]
      text = ""
      name = "Shafie Mukhre"
      position = "iOS Developer"
      image = "images/profilepic/shafie.png"
    [params.testimonials.button]
      link = ""
      text = "Join Us!"

  # Footer uses navbar data
